K: 12
N_train: 5000
USE_CUDA: true
act: gelu
batch_size: 40
d_in: 1
d_out: 2
device: gpu
epochs: 200
get_grid: true
input_data_path: data/grad_training_data/input_data_grad.pt
lr: 0.001
model_name: grad_xy_grid
n_layers: 4
output_data_path: data/grad_training_data/output_data_grad.pt
periodic_grid: false
seed: 1989
width: 64
