K: 18
N_train: 2000
USE_CUDA: true
act: gelu
batch_size: 25
d_in: 3
d_out: 1
device: gpu
epochs: 1
get_grid: true
input_data_path: data/smooth_training_data/A_to_chi1_input_data.pt
lr: 0.001
model_name: smooth_x_y_grid
n_layers: 4
output_data_path: data/smooth_training_data/A_to_chi1_output_data.pt
periodic_grid: false
seed: 1989
test_err_final: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDgAAADk0Njg0NzY3MTEzMDA4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ2
    ODQ3NjcxMTMwMDhxAWEuAQAAAAAAAADNEP8/
- 0
- !!python/tuple []
- !!python/tuple []
- false
- !!python/object/apply:collections.OrderedDict
  - []
train_err_final: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDgAAADk0Njg0NzY3MjAzNTUycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ2
    ODQ3NjcyMDM1NTJxAWEuAQAAAAAAAACUwpE/
- 0
- !!python/tuple []
- !!python/tuple []
- false
- !!python/object/apply:collections.OrderedDict
  - []
width: 64
