K: 18
N_train: 3000
USE_CUDA: true
act: gelu
batch_size: 40
d_in: 3
d_out: 1
device: gpu
epochs: 100
get_grid: true
input_data_path: data/smooth_training_data/A_to_chi1_input_data.pt
lr: 0.001
model_name: smooth_x_y_grid
n_layers: 5
output_data_path: data/smooth_training_data/A_to_chi1_output_data.pt
periodic_grid: false
seed: 1989
width: 64
