K: 12
N_train: 100
USE_CUDA: true
act: gelu
batch_size: 20
d_in: 3
d_out: 1
device: gpu
epochs: 2
get_grid: true
input_data_path: data/smooth_training_data/A_to_chi1_tiny_input_data.pt
lr: 0.001
model_name: smooth_periodic_grid
n_layers: 4
output_data_path: data/smooth_training_data/A_to_chi1_tiny_output_data.pt
periodic_grid: true
seed: 1989
width: 64
