K: 12
N_train: 9000
USE_CUDA: true
act: gelu
batch_size: 40
d_in: 3
d_out: 1
device: gpu
epochs: 300
get_grid: true
input_data_path: data/smooth_training_data/A_to_chi1_input_data.pt
lr: 0.001
model_name: smooth_x_y_grid_subsampling_on
n_layers: 4
output_data_path: data/smooth_training_data/A_to_chi1_output_data.pt
periodic_grid: false
seed: 1989
subsampling: true
width: 64
