K: 18
device: gpu
get_grid: True
periodic_grid: True
n_layers: 4
seed: 1989
width: 64
act: 'gelu'
epochs: 1
batch_size: 5
lr: 0.001
d_in: 3
d_out: 1
N_train: 15
USE_CUDA: True
model_name: 'smooth_periodic_grid'
input_data_path: 'data/smooth_training_data/A_to_chi1_tiny_input_data.pt'
output_data_path: 'data/smooth_training_data/A_to_chi1_tiny_output_data.pt'